### PR TITLE
Major refactor of how sysrepo callbacks is used in confd

### LINKED ISSUE #855: User admin sometimes fails to be added to 'wheel' group
Most likely this is caused by all other groups are handled with change_auth but wheel is handled by change_nacm (int ietf-system), and sometimes when the admin user should be added to wheel, the user admin does not exist. It says sys-cli also fails, but it is added to the user anyway.

Dec  4 14:04:18 ix confd[3290]: addgroup: unknown user admin
Dec  4 14:04:18 ix confd[3290]: Failed giving user "admin" UNIX sys-cli permissions.
Dec  4 14:04:18 ix confd[3290]: Failed giving user "admin" UNIX wheel permissions.
Dec  4 14:04:18 ix confd[3290]: addgroup: unknown user admin

To reproduce this:
run the test: ietf_system/upgrade in a loop on virtual devices.

### PR DESCRIPTION
**Pull request by mattiaswal**
Instead of having separate callbacks for each model, use **one** callback.
This allows us to handle dependencies between models in a controlled way,
Adding dependencies to the diff, before running the real change "callbacks".

Also fix some minor bugs.

Most likely fixes #855

## Checklist

Tick *relevant* boxes, this PR is-a or has-a:

- [x] Bugfix
  - [ ] Regression tests
  - [ ] ChangeLog updates (for next release)
- [ ] Feature
  - [ ] YANG model change => revision updated?
  - [ ] Regression tests added?
  - [ ] ChangeLog updates (for next release)
  - [ ] Documentation added?
- [x] Test changes
  - [x] Checked in changed Readme.adoc (make test-spec)
  - [ ] Added new test to group Readme.adoc and yaml file
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (please detail in commit messages)
- [ ] Build related changes
- [ ] Documentation content changes
  - [ ] ChangeLog updated (for major changes)
- [ ] Other (please describe):

### CODE REVIEW

File: src/confd/src/infix-services.c [hunk 1]
```diff
@@ -39,7 +36,13 @@
...
 #define SSHD_CONFIG_HOSTKEY SSHD_CONFIG_BASE "/host-keys.conf"
-
+#define LLDP_XPATH          "/ieee802-dot1ab-lldp:lldp"
+#define SSH_XPATH           "/infix-services:ssh"
+#define MDNS_XPATH          "/infix-services:mdns"
+#define WEB_XPATH           "/infix-services:web"
+#define WEB_RESTCONF_XPATH  WEB_XPATH"/restconf"
+#define WEB_NETBROWSE_XPATH WEB_XPATH"/netbrowse"
+#define WEB_CONSOLE_XPATH   WEB_XPATH"/console"
 typedef enum {
```
Comment (troglobit) [inline src/confd/src/infix-services.c]: Very nice cleanup, thanks!

**Comment by troglobit** [comment]
**Coverity** Last Build Status: In-queue. Your build is in the queue to be analyzed. There are 93 builds ahead of it.

**Review by troglobit — APPROVED** [review]
Nice work on this, very neat and clean!

We could also see Coverity Scan (eventually) didn't find anything relevant either, so this one is a GO from me! (After release plz ;-)
